package com.richware.chap14;

import java.io.*;

import java.math.BigInteger;

import java.security.*;

import javax.crypto.interfaces.*;
import javax.crypto.spec.*;
import javax.crypto.*;

import sun.misc.*;


/**
 * Class TestPBECiphers
 * Description: This is an example to
 * tests the PBE ciphers.
 *
 * Copyright:    Copyright (c) 2002 Wiley Publishing, Inc.
 * @author Rich Helton <rhelton@richware.com>
 * @version 1.0  01-FEB-2002
* DISCALIMER: Limit of Liability/Disclaimer of Warranty: 
* This code is used for educational purposes only. This software is provided "As Is" and 
* there are no implied warranties. While the publisher and author
* have used their best efforts in preparing this book and software, they make no
* representations or warranties and specifically disclaim any implied
* warranties of merchantability or fitness for a particular purpose. No
* warranty may be created or extended by sales representatives or written
* sales materials. The advice and strategies contained herein may not be
* suitable for your situation. You should consult with a professional where
* appropriate. Neither the publisher nor author shall be liable for any loss
* of profit or any other commercial damages, including but not limited to
* special, incidental, consequential, or other damages, including, but not limited to,
* procurement of substitute goods or services, loss of use, data, profits, or business
* interruption by cause of use or theory of use arising in any damage.
 */
public final class TestPBECiphers
 {
  /**
   * Constructor TestPBECiphers
   *
   *
   */
  public TestPBECiphers() {}

  /**
   * Method main
   * Description: This is a main test driver.
   *
   *
   * @param args none
   *
   */
  public static void main(String[] args)
   {

    try
     {

      /*
       * Message to encrypt/decrypt
       */
      String message = "This is a test, hackers beware.";

      /*
       * Set the password
       */
      char[] Password = new char[8];

      Password[0] = 'P';
      Password[1] = 'a';
      Password[2] = 's';
      Password[3] = 's';
      Password[4] = 'M';
      Password[5] = 'e';
      Password[6] = '2';
      Password[7] = '1';

      /*
       * Create the key from the password
       */
      PBEKeySpec keySpec = new PBEKeySpec(Password);

      /*
       * Form the secret key factory
       * for secretKey generation
       */
      SecretKeyFactory keyfactory =
        SecretKeyFactory.getInstance("PBEWithMD5AndDES");

      /*
       * Generate the secret key
       */
      SecretKey secretkey = keyfactory.generateSecret(keySpec);
      /*
       * Create a base-64 encoder for displaying binary data.
       */
      BASE64Encoder encoder = new BASE64Encoder();

      /*
       * Create a byte array from the message.
       */
      byte[] messageBytes = message.getBytes("UTF8");

      /*
       * Create the cipher algorithms
       * cipher is formatted algorithm/mode/padding or algorithm
       */
      Cipher cipher  = Cipher.getInstance("PBEWithMD5AndDES");
      Cipher cipher2 = Cipher.getInstance("PBEWithMD5AndDES");

      /*
       * Encrypt the message with the secret key.
       */
      cipher.init(Cipher.ENCRYPT_MODE, secretkey);

      byte[] encryptedMessage =
        cipher.doFinal(messageBytes, 0, messageBytes.length);

      System.out.println("Encrypted message:\n"
                         + encoder.encode(encryptedMessage));

      /*
       * retrieve parameters generated by underlying cipher
       * implementation
       */
      AlgorithmParameters algParams = cipher.getParameters();
      Class               PBEClass  =
        Class.forName("javax.crypto.spec.PBEParameterSpec");

      /*
       * get the PBEParameterSpec
       * to read the salt and IterationCount
       */
      PBEParameterSpec spec =
        (PBEParameterSpec) algParams
          .getParameterSpec(PBEClass);

      /*
       * Get the salt and iteration geenearated by the cipher
       * implementation
       */
      System.out.println("Salt:"
                         + encoder.encode(spec.getSalt()));
      System.out.println("IterationCount:"
                         + spec.getIterationCount());

      /*
       * Decrypt the message with the secret key.
       * PBE Decryption requires algorithm parameters
       * The algorithm parameters include Salt and iteration
       */
      cipher2.init(Cipher.DECRYPT_MODE, secretkey, algParams);

      byte[] decryptedMessage       =
        cipher2.doFinal(encryptedMessage, 0,
                        encryptedMessage.length);
      String decryptedMessageString =
        new String(decryptedMessage, "UTF8");

      System.out.println("\nDecrypted message: "
                         + decryptedMessageString);

      /*
       * Check that the decrypted message and the original
       * message are the same.
       */
      if (decryptedMessageString.equals(message))
       {
        System.out.println("\nTest succeeded.");
      }
      else
       {
        System.out.println("\nTest failed.");
      }
    }

    /*
     * Catches
     */
    catch (Exception ex)
     {
      ex.printStackTrace();
    }
  }
}
